@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('ContDownload_Master')
        {
         steps
          {
            script
             {
               cicd.gitDownload("maven") 
             }
          }
        }
        stage('ContBuild_Master')
        {
            steps
            {
                script
                {
                    cicd.mavenBuild()
                }
            }
        }
        stage('ContDeploy_Master')
        {
            steps
            {
                script
                {
                    cicd.tomcatDeploy("DeclarativepipelinewithsharedLibrary","172.31.34.184","testapp")
                }
            }
        }
        stage('ContTesting_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("FunctionalTesting")
                    cicd.executeSelenium("DeclarativepipelinewithsharedLibrary")
                }
            }
        }
        stage('ContDelivery_Master')
        {
            steps
            {
                script
                {
                    cicd.tomcatDeploy("DeclarativepipelinewithsharedLibrary","172.31.45.158","prodapp")
                }
            }
        }
    }
}
